import {
  NUMBER_FIVE_HUNDRED_NINETY_NINE,
  NUMBER_FIVE_HUNDRED_THREE,
  NUMBER_FOUR_HUNDRED_ONE,
  NUMBER_TWO_HUNDRED,
  NUMBER_TWO_THOUSAND,
  NUMBER_ZERO,
} from './numbers.const';

export const HTTP_NETWORK_STATUS = NUMBER_ZERO;
export const HTTP_UNAUTHORIZED = NUMBER_FOUR_HUNDRED_ONE;
export const HTTP_SERVICE_UNAVAILABLE = NUMBER_FIVE_HUNDRED_THREE;
export const HTTP_STATUS_MIN = NUMBER_TWO_HUNDRED;
export const HTTP_STATUS_MAX = NUMBER_FIVE_HUNDRED_NINETY_NINE;
export const RESPONSE_SNIPPET_MAX = NUMBER_TWO_THOUSAND;

export const HTTP_METHOD_GET = 'GET';
export const HTTP_METHOD_POST = 'POST';
export const HTTP_METHOD_PUT = 'PUT';
export const HTTP_METHOD_PATCH = 'PATCH';
export const HTTP_METHOD_DELETE = 'DELETE';
export const HTTP_METHOD_HEAD = 'HEAD';
export const HTTP_METHOD_OPTIONS = 'OPTIONS';
export const HTTP_METHOD_REQUEST = 'REQUEST';
